### ISSUE TITLE
Darkmode/Lightmode functionality

### ISSUE THREAD

**Issue by aspauldingcode** [aspauldingcode/.dotfiles#27]
Darkmode/Lightmode functionality

Problem:
Detecting system-wide theme as dark/light is not going so well on NixOS. In addtion, my themes are defined through nix-colors, so switching the color-scheme is essential to work universally across all my applications, including:
- brave-browser
- alacritty
- nvim
- waybar
- sketchybar
- qt
- gtk
- .car (macOS inject .car colorscheme files using SIMBL and SIMBL Loader such as MacForge)!

### _Tasks:_

- [ ] waybar darkmode button toggle
- [ ] sketchybar darkmode button toggle
- [ ] hotreload sketchybar on theme switch instead of pkill and restart it. (Install darkmode scheme switcher plugin)
- [ ] does waybar hotreload colors? hotreload waybar on color-scheme switch instead of pkill and restart it.
- [ ] alacritty hot-reload on colorscheme switch
- [ ] Brave Browser hot-reload colorscheme switch
- [ ] Dark colorscheme! 
- [ ] Light colorscheme!
- [ ] Detect system dark/light, and switch nix-color scheme to dark/light variant.
- [ ] Waybar Toggle switches systemwide dark/light variants. 
- [ ] Brave Browser chrome theme config switch? use jquery?
- [ ] Brave Browser DarkReader theme config switch? use jquery?
- [ ] Neovim/NixVim color theme scheme switch based off nix-colors.

**Comment by aspauldingcode** [comment]
What a hot mess.

**Comment by aspauldingcode** [comment]
macOS (NIXY) is successfully changing configuration of macOS system darkmode to light if the theme variant is lightmode from nix-colors.

Using nix specialization, I could create a toggle-theme to switch between a specified darkmode and lightmode colorscheme with nix colors (eg. gruvbox-soft-dark and gruvbox-soft-light).

To get this working on NixOS might be trivial from here.
